config/routes.rb
Rails.application.routes.draw do
  
  root 'teachers#index'
  
  get 'about' => 'static#about'
  
  resources :teachers do
    resources :students 
  end
  
  resources :students, only: [] do
      resources :logs
    end

end

app/models/log.rb
class Log < ActiveRecord::Base
    belongs_to :student
end

app/models/static.rb
class Static < ActiveRecord::Base
    def about
    end
end

app/models/student.rb
class Student < ActiveRecord::Base
    belongs_to :teacher
    has_many :logs
    
    before_save :upperCase
    
    def upperCase
        self.name = self.name.titleize
    end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_many :students
    
    before_save :upperCase
    
    def upperCase
        self.name = self.name.titleize
        self.primaryInstrument = self.primaryInstrument.titleize
        self.location = self.location.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @student = Student.find(params[:student_id])
    @teacher = Teacher.find(@student.teacher_id)
    @log = @student.logs.find(params[:id])
  end

  # GET /logs/new
  def new
    @student = Student.find(params[:student_id])
    @log = @student.logs.new
  end

  # GET /logs/1/edit
  def edit
    @student = Student.find(params[:student_id])
    @log = @student.logs.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    @student = Student.find(params[:student_id])
    @log = @student.logs.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to teacher_student_path(@student.teacher_id, @student), notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    @student = Student.find(params[:student_id])
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to student_log_path(@student, @log), notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @student = Student.find(params[:student_id])
    @teacher = Teacher.find(@student.teacher_id)
    @log.destroy
    respond_to do |format|
      format.html { redirect_to teacher_student_path(@teacher, @student), notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:teacher_id, :studentId, :comment)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def welcome
        @counter = 1
        @teachers = Teacher.all
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @teacher = Teacher.find(params[:teacher_id])
  end

  # GET /students/1
  # GET /students/1.json
  def show
    
    @teacher = Teacher.find(params[:teacher_id])
    @logs = @student.logs.order("created_at DESC").all
  end

  # GET /students/new
  def new
    @teacher = Teacher.find(params[:teacher_id])
    @student = @teacher.students.new
  end

  # GET /students/1/edit
  def edit
    @teacher = Teacher.find(params[:teacher_id])
    @student = @teacher.students.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @teacher = Teacher.find(params[:teacher_id])
    @student = @teacher.students.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to teacher_student_path(@teacher, @student), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    @teacher = Teacher.find(params[:teacher_id])
    @student = @teacher.students.find(params[:id])
    
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to teacher_student_path(@teacher, @student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @teacher = Teacher.find(params[:teacher_id])
    @student.destroy
    respond_to do |format|
      format.html { redirect_to teacher_path(@teacher), notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :teacher_id)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @counter = 1
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @students = @teacher.students
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :primaryInstrument, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicStudio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class = "navbar navbar-inverse navbar-static_top">

  <div class = "container">
    <div class = "navbar-brand"><%= link_to("MusicStudio", teachers_path) %></div>
    
    <button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
      <span class = "icon-bar"></span>
      <span class = "icon-bar"></span>
      <span class = "icon-bar"></span>
    </button>
    <div class = "collapse navbar-collapse navHeaderCollapse">
      
      <ul class = "nav navbar-nav navbar-right">
      
        <li><%= link_to("Home", teachers_path, :class => "active") %></li>
        <li><%= link_to("About", about_path) %></li>
        
      </ul>
    </div>
  </div>

</div>

<%= yield %>

</body>
</html>

app/views/logs/_form.html.erb
<div class = "container">
<%= form_for([@student, @log], html: {:class => "form-horizontal"}) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :teacher_id, value: @student.teacher_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :student_id, value: @student.id %>
  </div>
  <div class="form-group">
    <%= f.label :comment, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :comment, :autofocus => true, :class => "form-control", :rows => "10" %>
    </div>
  </div>
 
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= f.submit "Update Log", :class => "btn btn-default btn-block" %>
    </div>
    
<% end %>

<!--<%= form_for [@student, @log] do |f| %>-->
<!--  <% if @log.errors.any? %>-->
<!--    <div id="error_explanation">-->
<!--      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>-->

<!--      <ul>-->
<!--      <% @log.errors.full_messages.each do |message| %>-->
<!--        <li><%= message %></li>-->
<!--      <% end %>-->
<!--      </ul>-->
<!--    </div>-->
<!--  <% end %>-->

<!--  <div class="field">-->
<!--    <%= f.hidden_field :teacher_id, value: @student.teacher_id %>-->
<!--  </div>-->
<!--  <div class="field">-->
<!--    <%= f.hidden_field :student_id, value: @student.id %>-->
<!--  </div>-->
<!--  <div class="field">-->
<!--    <%= f.label :comment %><br>-->
<!--    <%= f.text_area :comment %>-->
<!--  </div>-->
<!--  <div class="actions">-->
<!--    <%= f.submit %>-->
<!--  </div>-->
<!--<% end %>-->

app/views/logs/edit.html.erb
<div class = "container text-center">
    <h1>Editing Log</h1>
</div>

<%= render 'form' %>

<div class="col-sm-4">
    <%= link_to('Cancel', teacher_student_path(@student.teacher_id, @student), :class => "btn btn-warning btn-block voffset2") %>
</div>
<div class = "col-sm-4">
    <%= button_to('Delete Log

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table>
  <thead>
    <tr>
      <th>teacher_id</th>
      <th>Studentid</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.teacher_id %></td>
        <td><%= log.studentId %></td>
        <td><%= log.comment %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<div class = "container text-center">
    <h1>New Log!</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-6 col-sm-2">
      <%= link_to('Cancel', teacher_student_path(@student.teacher_id, @student), :class => "btn btn-warning btn-block voffset2") %>
</div>

app/views/logs/show.html.erb
<div class = "container">
  <div class = "jumbotron text-center">
  
    <h2><p id="notice"><%= notice %></p></h2>
    <h1>Practice Log Entry for <%= @student.name %></h1>
    <h3>Created <%= @log.created_at.strftime("%B %d, %Y") %> by <%= @teacher.name %></h3>
    
  </div>
</div>

<div class = "container text-center center-block">

  <div class = "panel panel-default">
    <div class = "panel-body">
      <%= @log.comment %>
    </div>
  </div>
  
  <div class = "row">
    <div class = "col-sm-4">
      <%= link_to(teacher_student_path(@teacher, @student), :class => "btn btn-success btn-lg active btn-block voffset3") do %>
        Back to <%= @student.name %>
      <% end %>
    </div>
    <div class = "col-sm-4">
      <%= link_to('Edit Log', edit_student_log_path(@student, @log), :class => "btn btn-warning btn-lg active btn-block voffset3") %>
    </div>
    <div class = "col-sm-4">
      <%= button_to('Delete Log', student_log_path(@student, @log), method: "delete", data: { confirm: "Are you sure?" }, :class => "btn btn-danger btn-lg active btn-block voffset3") %>
    </div>
</div>

app/views/students/_form.html.erb
<div class = "container">
<%= form_for([@teacher, @student], html: {:class => "form-horizontal"}) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :autofocus => true, :class => "form-control" %>
    </div>
  </div>
 
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
      <%= f.submit "Update Student", :class => "btn btn-default btn-block voffset2" %>
    </div>
    
<% end %>



<!--<%= form_for [@teacher, @student] do |f| %>-->
<!--  <% if @student.errors.any? %>-->
<!--    <div id="error_explanation">-->
<!--      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>-->

<!--      <ul>-->
<!--      <% @student.errors.full_messages.each do |message| %>-->
<!--        <li><%= message %></li>-->
<!--      <% end %>-->
<!--      </ul>-->
<!--    </div>-->
<!--  <% end %>-->

<!--  <div class="field">-->
<!--    <%= f.label :name %><br>-->
<!--    <%= f.text_field :name %>-->
<!--  </div>-->
<!--  <div class="actions">-->
<!--    <%= f.submit %>-->
<!--  </div>-->
<!--<% end %>-->

app/views/students/edit.html.erb
<div class = "container text-center">
    <h1>Editing Student</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-1 col-sm-3">
      <%= link_to('Cancel', teacher_student_path(@teacher, @student), :class => "btn btn-warning btn-block voffset2") %>
</div>
<div class="col-sm-3">
    <%= button_to('Delete Student', teacher_student_path(@teacher, @student), method: "delete", data: { confirm: "Are you sure?" }, :class => "btn btn-danger btn-block voffset2") %>
</div>

<!--<%= link_to 'Show', teacher_student_path(@teacher, @student) %> |-->
<!--<%= link_to 'Back', teacher_students_path %>-->

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>teacher_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.teacher_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_teacher_students_path(@teacher) %>

app/views/students/new.html.erb
<div class = "container text-center">
    <h1>New Student</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-5 col-sm-2">
      <%= link_to('Cancel', teacher_path(@teacher), :class => "btn btn-warning btn-block voffset2") %>
</div>

app/views/students/show.html.erb
<div class = "container">
  <div class = "jumbotron text-center">
    <h2><p id="notice"><%= notice %></p></h2>
    <h1>Welcome <%= @student.name %>!</h1>
    <h3>Studying under <%= @teacher.name %></h3>
  </div>
</div>

<div class = "container text-center">
  <div class = "row">
    <div class = "col-sm-12">
      <%= link_to(new_student_log_path(@student), :class => "btn btn-success btn-lg active btn-block voffset3") do %>
        <h2>Add A New Log!</h2>
      <% end %>
    </div>
    <div class = "col-sm-12">
      <h2>Now Showing <%= pluralize(@student.logs.count, "Practice Log") %></h2>
    </div>
  </div>
  
  <div class = "row">
    <% @logs.each do |log| %>
      <div class = "col-md-4">
      
        <%= link_to(student_log_path(@student, log), :class => "btn btn-default btn-lg active btn-block voffset3") do %>
          <h2><%= log.created_at.strftime("%B %d, %Y") %></h2>
          
          <h3>"<%= log.comment.truncate(30, separator: ' ', omission: '...') %>"</h3>
        <% end %>
      
      </div>
    <% end %>
  </div>
  
  <div class = "row">
    <div class = "col-sm-4">
      <%= link_to(teacher_path(@teacher), :class => "btn btn-success btn-lg active btn-block voffset3") do %>
        Back to <%= @teacher.name %>
      <% end %>
    </div>
    <div class = "col-sm-4">
      <%= link_to('Edit Student', edit_teacher_student_path(@teacher, @student), :class => "btn btn-warning btn-lg active btn-block voffset3") %>
    </div>
    <div class = "col-sm-4">
      <%= link_to('Back to Teacher List', teachers_path, :class => "btn btn-primary btn-lg active btn-block voffset3") %>
    </div>
    

<!--<p>-->
<!--  <strong>Name:</strong>-->
<!--  <%= @student.name %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Teacher:</strong>-->
<!--  <%= link_to(@teacher.name, @teacher) %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong><%= link_to("Add A New Log", new_student_log_path(@student)) %></strong>-->
<!--<p>-->
<!--  <strong>Previous Logs</strong>-->
<!--  <ul>-->
<!--  <% @logs.each do |log| %>-->
<!--    <li>-->
<!--    <%= link_to(log.created_at, student_log_path(@student, log)) %>-->
<!--    </li>-->
<!--  <% end %>-->
<!--  </ul>-->
<!--</p>-->

<!--<%= link_to 'Edit', edit_teacher_student_path(@teacher, @student) %> |-->
<!--<%= link_to 'Back', teacher_path(@teacher) %>-->

app/views/teachers/_form.html.erb
<div class = "container">
<%= form_for(@teacher, html: {:class => "form-horizontal"}) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :autofocus => true, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Primary Instrument", :class => "col-sm-2 control-label  vertical-center" %>
    <div class="col-sm-10">
      <%= f.text_field :primaryInstrument, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
      <%= f.submit "Update Teacher", :class => "btn btn-default voffset2" %>
    </div>
    
<% end %>

app/views/teachers/edit.html.erb
<div class = "container text-center">
    <h1>Editing Teacher</h1>
</div>
    
<%= render 'form' %>

<div class="col-sm-offset-2 col-sm-3">
      <%= link_to('Cancel', teacher_path(@teacher), :class => "btn btn-warning btn-block voffset2") %>
</div>
<div class="col-sm-3">
    <%= button_to('Delete Teacher', teacher_path(@teacher), method: "delete", data: { confirm: "Are you sure?" }, :class => "btn btn-danger btn-block voffset2") %>
</div>
    

app/views/teachers/index.html.erb
<div class = "container">

    <div class = "jumbotron text-center">
    
        <h1>MusicStudio</h1>
        <p>Welcome to MusicStudio, the new WebApp for use by music professionals to help track their students.
        <p>This is a VERY EARLY BETA! Be aware of many bugs and issues<p>
        <p>Currently there are no personal accounts.</p>
        
    </div>

</div>

<div class = "container text-center">

    <div class = "row">
        <div class = "col-sm-12">
            <h2>Now Showing <%= pluralize(Teacher.all.count, "Available Teacher") %></h2>
        </div>
    </div>

    <div class = "row">
    <% @teachers.each do |teacher| %>
        <% if @counter % 4 == 0 %>
            </div>
            <div class = "row">
        <% end %>
    
        <div class = "col-sm-4">
            <%= link_to(teacher_path(teacher), :class => "btn btn-default btn-lg active btn-block voffset2") do %>
                <h2><%= teacher.name %></h2>
                <h3><%= teacher.primaryInstrument %></h3>
            <% end %>
        
        </div>
    <% @counter += 1 %>
    <% end %>
    
    </div>
    
    <div class = "row">
        <div class = "col-sm-12">
            <%= link_to("Add New Teacher", new_teacher_path, :class => "btn btn-success btn-lg btn-block voffset2") %>
        </div>
    </div>

</div>

<!--<h1>Listing teachers</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Name</th>-->
<!--      <th>Primaryinstrument</th>-->
<!--      <th>Location</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @teachers.each do |teacher| %>-->
<!--      <tr>-->
<!--        <td><%= teacher.name %></td>-->
<!--        <td><%= teacher.primaryInstrument %></td>-->
<!--        <td><%= teacher.location %></td>-->
<!--        <td><%= link_to 'Show', teacher %></td>-->
<!--        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>-->
<!--        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Teacher', new_teacher_path %>-->

app/views/teachers/new.html.erb
<div class = "container text-center">
    <h1>New Teacher</h1>
</div>

<%= render 'form' %>

<div class="col-sm-offset-6 col-sm-2">
      <%= link_to('Cancel', teachers_path, :class => "btn btn-warning btn-block voffset2") %>
</div>

app/views/teachers/show.html.erb
<div class = "container">
  <div class = "jumbotron text-center">
    <h2><p id="notice"><%= notice %></p></h2>
    <h1>Welcome <%= @teacher.name %>!</h1>
    <h3>Working out of <%= @teacher.location %></h3>
  </div>
</div>

<div class = "container text-center">
  <div class = "row">
    <div class = "col-sm-12">
      <h2>Now Showing <%= pluralize(@teacher.students.count, "Student") %></h2>
    </div>
  </div>
  
  <div class = "row">
    <% @students.each do |student| %>
    <div class = "col-sm-4">
    
      <%= link_to(teacher_student_path(@teacher, student), :class => "btn btn-default btn-lg active btn-block voffset3") do %>
         <h2><%= student.name %></h2>
      <% end %>
        
    </div>
    <% end %>
  </div>
  
  <div class = "row">
    <div class = "col-sm-4">
      <%= link_to("Add Student", new_teacher_student_path(@teacher), :class => "btn btn-success btn-lg active btn-block voffset3") %>
    </div>
    <div class = "col-sm-4">
      <%= link_to('Edit Teacher', edit_teacher_path(@teacher), :class => "btn btn-warning btn-lg active btn-block voffset3") %>
    </div>
    <div class = "col-sm-4">
      <%= link_to('Back to Teacher List', teachers_path, :class => "btn btn-primary btn-lg active btn-block voffset3") %>
    </div>
  </div>
</div>